[project]
name = "api"
version = "0.1.0"
description = "Prism API"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.115.14",
]

[dependency-groups]
dev = [
    "ruff>=0.12.2",
]
